import 'package:flutter_test/flutter_test.dart';
import 'package:zitlas_mobile/features/diet/models/diet_meal.dart';
import 'package:zitlas_mobile/features/diet/models/diet_plan_content.dart';

/// The Diet tree is generated by the same LLM pipeline as the workout tree,
/// so it carries the same latent `String`-where-`num?`-expected defect that
/// crashed `WorkoutExercise.sets` on-device. These tests cover it
/// pre-emptively rather than waiting for the same crash in `diet_plan`.
///
/// The website absorbed the variance through JS concatenation —
/// `(meal.calories || 0) + ' kcal · ' + (meal.protein_g || 0) + 'g protein'`
/// (ai-coach.js:1991) — which never cared about the runtime type.
void main() {
  group('DietMeal.fromMap — numeric fields tolerate LLM type drift', () {
    test('calories/protein as strings do not throw and coerce to numbers', () {
      final meal = DietMeal.fromMap(const {
        'meal_name': 'Breakfast',
        'time': '8:00 AM',
        'foods': ['Oats', 'Banana'],
        'calories': '350',
        'protein_g': '18',
      });
      expect(meal.calories, 350);
      expect(meal.proteinG, 18);
    });

    test('unit-suffixed numerics are coerced like the website parseInt path', () {
      final meal = DietMeal.fromMap(const {
        'meal_name': 'Lunch',
        'calories': '520 kcal',
        'protein_g': '32 g',
      });
      expect(meal.calories, 520);
      expect(meal.proteinG, 32);
    });

    test('real numbers still parse unchanged', () {
      final meal = DietMeal.fromMap(const {'meal_name': 'X', 'calories': 400, 'protein_g': 25.5});
      expect(meal.calories, 400);
      expect(meal.proteinG, 25.5);
    });

    test('null / missing / unparseable numerics stay null (never a fake 0)', () {
      expect(DietMeal.fromMap(const {'meal_name': 'X'}).calories, isNull);
      expect(DietMeal.fromMap(const {'meal_name': 'X', 'calories': null}).calories, isNull);
      expect(DietMeal.fromMap(const {'meal_name': 'X', 'calories': 'unknown'}).calories, isNull);
    });

    test('foods tolerates a non-list and non-string entries', () {
      expect(DietMeal.fromMap(const {'meal_name': 'X', 'foods': 'Oats'}).foods, isEmpty);
      expect(
        DietMeal.fromMap(const {'meal_name': 'X', 'foods': ['Oats', 2, null]}).foods,
        ['Oats', '2', 'null'],
      );
    });

    test('meal_name falls back to name, then to "Meal"', () {
      expect(DietMeal.fromMap(const {'name': 'Snack'}).mealName, 'Snack');
      expect(DietMeal.fromMap(const {}).mealName, 'Meal');
    });

    test('mealKey slugification is unaffected by the coercion change', () {
      expect(DietMeal.fromMap(const {'meal_name': 'Mid-Morning Snack'}).mealKey, 'mid_morning_snack');
    });
  });

  group('DietPlanContent.fromMap — full diet_plan response shape', () {
    test('parses a realistic response with mixed numeric types', () {
      final plan = DietPlanContent.fromMap(const {
        'plan_name': '7-Day Weight Loss Meal Plan',
        'daily_calories_target': '1731',
        'daily_protein_target_g': 150,
        'summary': 'Built around your hostel mess.',
        'key_rules': ['Drink 3L water', 'No sugar after 8pm'],
        'days': [
          {
            'day': 'Monday',
            'theme': 'Light start',
            'meals': [
              {'meal_name': 'Breakfast', 'foods': ['Poha'], 'calories': '300', 'protein_g': 10},
            ],
          },
        ],
      });

      expect(plan.planName, '7-Day Weight Loss Meal Plan');
      expect(plan.dailyCaloriesTarget, 1731);
      expect(plan.dailyProteinTargetG, 150);
      expect(plan.keyRules, hasLength(2));
      expect(plan.days.single.meals.single.calories, 300);
    });

    test('missing / null / non-list days degrade to empty, not a crash', () {
      expect(DietPlanContent.fromMap(const {}).days, isEmpty);
      expect(DietPlanContent.fromMap(const {'days': null}).days, isEmpty);
      expect(DietPlanContent.fromMap(const {'days': 'none'}).days, isEmpty);
      expect(DietPlanContent.fromMap(null).days, isEmpty);
    });

    test('non-map day entries are skipped rather than fatal', () {
      final plan = DietPlanContent.fromMap(const {
        'days': [
          {'day': 'Mon', 'meals': []},
          'garbage',
        ],
      });
      expect(plan.days, hasLength(1));
    });

    test('key_rules tolerates a non-list', () {
      expect(DietPlanContent.fromMap(const {'key_rules': 'nope'}).keyRules, isEmpty);
    });
  });
}
